#!/usr/bin/env bash
# Render the Homebrew formula for a release. Reads per-asset sha256 from a
# checksums dir (files named skillrot-<os>-<arch>.sha256, each holding the bare
# hash) and prints Formula/skillrot.rb to stdout.
#
# Usage: render-formula.sh <version> <checksums-dir>
set -euo pipefail

VERSION="${1:?version required, e.g. 0.2.0}"
SUMS="${2:?checksums dir required}"
BASE="https://github.com/mishanefedov/skillrot/releases/download/v${VERSION}"

sha() { cat "$SUMS/skillrot-$1.sha256" | awk '{print $1}'; }

cat <<EOF
# Generated by scripts/render-formula.sh on release. Do not edit by hand.
class Skillrot < Formula
  desc "Audit agent skills for CLI drift — flags/subcommands the installed tool no longer accepts"
  homepage "https://github.com/mishanefedov/skillrot"
  version "${VERSION}"
  license "MIT"

  on_macos do
    on_arm do
      url "${BASE}/skillrot-darwin-arm64"
      sha256 "$(sha darwin-arm64)"
    end
    on_intel do
      url "${BASE}/skillrot-darwin-x64"
      sha256 "$(sha darwin-x64)"
    end
  end

  on_linux do
    on_arm do
      url "${BASE}/skillrot-linux-arm64"
      sha256 "$(sha linux-arm64)"
    end
    on_intel do
      url "${BASE}/skillrot-linux-x64"
      sha256 "$(sha linux-x64)"
    end
  end

  def install
    bin.install Dir["skillrot-*"].first => "skillrot"
  end

  test do
    assert_match "skillrot", shell_output("#{bin}/skillrot --help")
  end
end
EOF
